### ISSUE TITLE
typingSpeed is incorrectly referred to in the docs

### ISSUE THREAD

**Issue by FROSTB1T** [BraisC/react-text-typist#1]
Firstly, love the library. Small and simple, it's exactly what I was looking for.

Just wanted to point out a small issue with the readme that caught me off guard, it refers to "writeSpeed" which it looks like you have since renamed to typingSpeed.

Thanks for the hard work!

**Comment by BraisC** [comment]
Thank you very much for your help and also for your kind wors, much appreciated 🙌
Fixed in ab5575f0c0e6d36a620e07b5c26a9c3684eb9c47

Thanks!
