### ISSUE TITLE
1.1.4 typing speed is super slow 

### ISSUE THREAD

**Issue by ostenloo** [BraisC/react-text-typist#11]
I was just testing out this package and the 1.1.4 seems to have a bug with the typing speed? I re-installed version 1.1.0 and it worked fine.

**Comment by kaichii** [comment]
[code sandbox](https://codesandbox.io/s/react-text-typist-iln7v0?file=/src/App.js)

- 1.1.0
- 1.0.7
- 1.0.6
- 1.0.5
- 1.0.4
- 1.0.3
- 1.0.2
- 1.0.1
- 1.0.0 

The above versions worked fine, others are not worked properly.

**Comment by BraisC** [comment]
I just updated some dependencies because of Github security alerts, one of them must have broken something :(

Will take a look ASAP, sorry for the inconvenience

**Comment by BraisC** [comment]
Should be fixed now in version 1.1.5
