### ISSUE TITLE
Doesn't work with React 18

### ISSUE THREAD

**Issue by necheporenko** [BraisC/react-text-typist#12]
The latest version doesn't work with React 18, but I found that version 1.1.0 works fine.
https://codesandbox.io/s/react-text-typist-forked-lmzke0

**Comment by evro-eth** [comment]
Also having issues with React 18. Types out the first two letters and stops.

**Comment by BraisC** [comment]
> Also having issues with React 18. Types out the first two letters and stops.

Can you try a previous version? I will try to work on this ASAP

**Comment by chungweileong94** [comment]
> > Also having issues with React 18. Types out the first two letters and stops.
> 
> Can you try a previous version? I will try to work on this ASAP

No, same thing happens on previous version as well.

**Comment by chungweileong94** [comment]
> > > Also having issues with React 18. Types out the first two letters and stops.
> 
> > 
> 
> > Can you try a previous version? I will try to work on this ASAP
> 
> 
> 
> No, same thing happens on previous version as well.

Correction, it didn't work with 1.0.9 and the latest version, but it did on 1.1.0.

**Comment by BraisC** [comment]
Sorry for the delay, but it should be fixed now :)

**Comment by BraisC** [comment]
> The latest version doesn't work with React 18, but I found that version 1.1.0 works fine. https://codesandbox.io/s/react-text-typist-forked-lmzke0

Tested in this sandbox and it works fine, I am closing this issue now, so please, if it still happens open another issue, thanks for your help 🫶
