### ISSUE TITLE
Clear out all timeouts

### ISSUE THREAD

**Issue by kikoanis** [BraisC/react-text-typist#5]
Thanks for putting this together. 

You probably need to clear out all `setTimeout` handlers on component unmount, otherwise, you most likely will get the memory leak warning. 

```Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.```

Please let me know if I need to submit a PR.

**Comment by BraisC** [comment]
Hi, yep, you are correct.

You can submit a PR if you like, I would appreciate, otherwise I will fix it in the next couple of days as I am on vacation 

Thank you 🤗

**Comment by kikoanis** [comment]
Done!
